# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
#palette = "catppuccin_macchiato"

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
error_symbol = "[λ](bold #ff5555)"
success_symbol = "[λ](bold #50fa7b)"
#success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[aws]
style = "bold #ffb86c"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"
#[rust]
#symbol = " "

#[python]
#symbol = " "

#[palettes.catppuccin_macchiato]
#rosewater = "#f4dbd6"
#flamingo = "#f0c6c6"
#pink = "#f5bde6"
#mauve = "#c6a0f6"
#red = "#ed8796"
#maroon = "#ee99a0"
#peach = "#f5a97f"
#yellow = "#eed49f"
#green = "#a6da95"
#teal = "#8bd5ca"
#sky = "#91d7e3"
#sapphire = "#7dc4e4"
#blue = "#8aadf4"
#lavender = "#b7bdf8"
#text = "#cad3f5"
#subtext1 = "#b8c0e0"
#subtext0 = "#a5adcb"
#overlay2 = "#939ab7"
#overlay1 = "#8087a2"
#overlay0 = "#6e738d"
#surface2 = "#5b6078"
#surface1 = "#494d64"
#surface0 = "#363a4f"
#base = "#24273a"
#mantle = "#1e2030"
#crust = "#181926"
