vim.filetype.add({
  extension = {
    pnd = 'poweron',
    PND = 'poweron',
    po = 'poweron',
    PO = 'poweron',
    pro = 'poweron',
    PRO = 'poweron',
    def = 'poweron',
    DEF = 'poweron',
    sub = 'poweron',
    SUB = 'poweron',
    set = 'poweron',
    SET = 'poweron',
    fmp = 'poweron',
    FMP = 'poweron',
    fm = 'poweron',
    FM = 'poweron',
    inc = 'poweron',
    INC = 'poweron',
    symform = 'poweron',
    SYMFORM = 'poweron',
  },
  pattern = {
    ['.*.%d%d%d'] = 'poweron',
    ['EAR.*'] = 'poweron',
    ['ear.*'] = 'poweron',
    ['EMA.*'] = 'poweron',
    ['ema.*'] = 'poweron',
    ['ELA.*'] = 'poweron',
    ['ela.*'] = 'poweron',
    ['/home/phil/projects/SourceControl/Main/Client Work/186 - USF/Staff Augmentation/*.*'] = 'poweron',
    ['/home/phil/projects/poweron/*.*'] = 'poweron',
  }
})
