screenshot-directory=~/Downloads/Captures/Autosaved Captures.localized/screenshots/
ontop=yes
hls-bitrate=max
autofit-larger=50%x50%

profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample

