; highlights.scm

(comment) @comment
(keyword) @keyword
(target_division) @namespace
(define_division) @namespace
(setup_division) @namespace
(print_division) @namespace
(select_division) @namespace
(sort_division) @namespace
(letter_division) @namespace
(total_division) @namespace
(record_type) @type
(include_statement)  @include
(string_literal) @string
(data_type) @type.builtin
(array_type) @type.builtin
(number) @number
(procedure_call) @method
(procedure_definition) @keyword.function
(while_statement) @repeat
(foreachdoend) @repeat
(if_statement) @conditional
(date) @string
(rate) @number
(money) @string
(identifier) @variable
(for_loop) @repeat
(poweron_function) @function.builtin
