#!/usr/bin/env bash

if [ -z "$SYSNAME" ]; then 
 session=$(find ~ ~/projects/ ~/projects/SourceControl/Main/Client\ Work/ -mindepth 1 -maxdepth 1 -type d | fzf)
else
 session=$(find ~ ~/projects/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi
session_name=$(basename "$session" | tr . _)
command=""

if ! tmux has-session -t "$session_name" 2>/dev/null; then 
  if [[ $session_name =~ ^[0-9]+*$ ]]; then 
    command="/home/phil/bin/TEE-CLC-14.137.0/tf get -recursive $session"
  fi
  tmux new-session -d -s "$session_name" -c "$session" 
fi 

tmux switch-client -t "$session_name" 
